package com.cognizant.entity;

import jakarta.persistence.*;

/**
 * Employee Entity
 *
 * <p>Represents a persistent employee record mapped to the "employees" table
 * in the relational database. Spring Data JPA / Hibernate will automatically
 * create and manage the underlying table schema based on this class definition
 * (when {@code spring.jpa.hibernate.ddl-auto=create-drop} is set).</p>
 *
 * <p><b>JPA Annotations used:</b>
 * <ul>
 *   <li>{@code @Entity}   - marks the class as a JPA managed entity</li>
 *   <li>{@code @Table}    - maps the class to a specific table name</li>
 *   <li>{@code @Id}       - designates the primary key field</li>
 *   <li>{@code @GeneratedValue} - auto-generates the PK value (IDENTITY strategy
 *       lets the database assign the next available integer)</li>
 *   <li>{@code @Column}   - fine-tunes column properties (nullability, length…)</li>
 * </ul>
 * </p>
 *
 * @author  Cognizant Nurture – Java FSE Program
 * @version 1.0
 * @since   Week 2 – Spring Data JPA Module
 */
@Entity
@Table(name = "employees")
public class Employee {

    // =========================================================================
    // Fields
    // =========================================================================

    /**
     * Primary key – auto-generated by the database using the IDENTITY strategy.
     * H2 will use an auto-increment column; other databases (MySQL, PostgreSQL)
     * behave similarly.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Employee's first name.
     * {@code nullable = false} enforces a NOT NULL constraint at the DB level.
     * {@code length = 50} caps the VARCHAR column at 50 characters.
     */
    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;

    /**
     * Employee's last name.
     */
    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;

    /**
     * Employee's email address – must be unique across all records.
     * The {@code unique = true} attribute adds a UNIQUE constraint to the column.
     */
    @Column(name = "email", nullable = false, unique = true, length = 100)
    private String email;

    /**
     * Department the employee belongs to (e.g., "Engineering", "Finance").
     */
    @Column(name = "department", nullable = false, length = 100)
    private String department;

    /**
     * Annual salary of the employee in the base currency (USD by default).
     * Stored as a DOUBLE PRECISION / FLOAT8 column.
     */
    @Column(name = "salary", nullable = false)
    private double salary;

    // =========================================================================
    // Constructors
    // =========================================================================

    /**
     * Default no-argument constructor required by the JPA specification.
     * JPA needs to instantiate entities via reflection; if you only declare
     * parameterized constructors this will break at runtime.
     */
    public Employee() {
    }

    /**
     * Convenience constructor for creating a new {@code Employee} without
     * specifying an ID (the database will generate it).
     *
     * @param firstName  employee's first name
     * @param lastName   employee's last name
     * @param email      employee's unique email address
     * @param department department the employee belongs to
     * @param salary     employee's annual salary
     */
    public Employee(String firstName, String lastName, String email,
                    String department, double salary) {
        this.firstName  = firstName;
        this.lastName   = lastName;
        this.email      = email;
        this.department = department;
        this.salary     = salary;
    }

    /**
     * Full constructor including ID – useful for reconstructing an entity
     * fetched from an external source where the ID is already known.
     *
     * @param id         the database-assigned primary key
     * @param firstName  employee's first name
     * @param lastName   employee's last name
     * @param email      employee's unique email address
     * @param department department the employee belongs to
     * @param salary     employee's annual salary
     */
    public Employee(Long id, String firstName, String lastName, String email,
                    String department, double salary) {
        this.id         = id;
        this.firstName  = firstName;
        this.lastName   = lastName;
        this.email      = email;
        this.department = department;
        this.salary     = salary;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    /**
     * Returns the primary key of this employee record.
     *
     * @return the auto-generated database ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the primary key (typically managed by JPA – avoid calling manually).
     *
     * @param id the primary key value to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the employee's first name.
     *
     * @return first name string
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the employee's first name.
     *
     * @param firstName new first name value
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Returns the employee's last name.
     *
     * @return last name string
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the employee's last name.
     *
     * @param lastName new last name value
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Returns the employee's email address.
     *
     * @return email string
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the employee's email address.
     *
     * @param email new email value; must be unique in the database
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the department this employee belongs to.
     *
     * @return department name
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the employee's department.
     *
     * @param department new department name
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * Returns the employee's annual salary.
     *
     * @return salary as a {@code double}
     */
    public double getSalary() {
        return salary;
    }

    /**
     * Sets the employee's annual salary.
     *
     * @param salary new salary value; should be a positive number
     */
    public void setSalary(double salary) {
        this.salary = salary;
    }

    // =========================================================================
    // toString
    // =========================================================================

    /**
     * Returns a human-readable representation of the {@code Employee} object.
     * Useful for logging and debugging purposes.
     *
     * @return formatted string with all field values
     */
    @Override
    public String toString() {
        return "Employee{" +
                "id="          + id         +
                ", firstName='" + firstName  + '\'' +
                ", lastName='"  + lastName   + '\'' +
                ", email='"     + email      + '\'' +
                ", department='"+ department + '\'' +
                ", salary="     + salary     +
                '}';
    }
}
